### ISSUE TITLE
Math wrong with larger numbers, e.g. 10¹⁰⁰

### ISSUE THREAD

**Issue by Gumnos** [marcopaganini/rpn#14]
Somewhat surprised at the results when testing larger numbers:

    $ dc
    10 100 ^ p
    10000000000000000000000000000000000000000000000000000000000000000000\
    000000000000000000000000000000000

Comparing the expected results with the output of `rpn`:

    $ ./rpn
    10 100 ^
    = 10000000000000002101697803323328251387822715387464188032188166609887360023982790799717755191065313280 (10,000,000,000,000,002,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000)

Both the unformatted & formatted numbers are wrong (it should be a 1 followed by 100 zeroes, clearly wrong in the unformatted result, and a strange "2" ended up in the formatted output)

**Comment by marcopaganini** [comment]
This is a side effect of the float64 limitations. One option is to convert rpn to use big.Float. A more immediate one is to warn people in the page that it should not be used for integers larger than 2^53. See #13 for more details.
